# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET httpproxy with or without query parameters;
# * 'ptr' and 'ptrp' create a POST httpproxy with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST httpproxy to submit a form with a text or file field (multipart/form-data);

GET http://localhost:80

###
POST http://localhost:80
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"

field-value
--WebAppBoundary--

###